### ISSUE TITLE
get that stupid PID loop to work and not spend 7 seconds oscillating 

### ISSUE THREAD

**Issue by LHeadley** [Centennial-FTC-Robotics/Cypher2019-2020#16]

**Comment by LHeadley** [comment]
maybe making a graph with this https://github.com/acmerobotics/ftc-dashboard could help us and then also we have a fancy graph to put in notebook

**Comment by BC849** [comment]
good. Just be sure to like get the graph in by tues

**Comment by BC849** [comment]
We're not using new pid loop anymore so goodbye
