### ISSUE TITLE
figure out a magical way to make prototype auto AI

### ISSUE THREAD

**Issue by BC849** [Centennial-FTC-Robotics/Cypher2019-2020#22]
do after everything else is done but painfully figure out ai and maybe magically make auto machine learning work

**Comment by BC849** [comment]
aka those like gluten free

**Comment by LHeadley** [comment]
gf has paths that they just figured out for each stone configuration... no actual team had an AI because that's not really how they work. the problem with our auto is just time really. 3 stone auto isn't hard to program the hard part is doing it in 30 sec
