### ISSUE TITLE
run stone auto and then youll know whats wrong

### ISSUE THREAD

**Issue by LHeadley** [Centennial-FTC-Robotics/Cypher2019-2020#6]

**Comment by BC849** [comment]
possibly fixed? still hadn't tested new stone auto but will update

**Comment by LHeadley** [comment]
runs into wall after grabbing stone and wont stop moving forward...

**Comment by BC849** [comment]
make 2nd skystone work

**Comment by LHeadley** [comment]
works but takes time although general issue has been solved
